FairwindsOps/reckoner

- README.md
Command lines links in the readme are replaced by <a> links.
This leads to commands rendered as `pip install git+reactiveops/reckoner` which obviously does not work.
> Update readme to prevent link replacement

- reckoner/config.py
- reckoner/course.py
- tests/test_reckoner.py
Other small fixes to spelling, formatting, etc.
New output:
```
✓± reckoner  plot course.yaml --heading metrics-server
2019-01-07 16:17:35 root[25426]     INFO Installing metrics-server
2019-01-07 16:17:36 root[25426]    ERROR Missing requirement environment variable: METRIC_RESOLUTION
2019-01-07 16:17:36 root[25426]    ERROR Helm upgrade failed. Rolling back metrics-server
2019-01-07 16:17:36 root[25426]    ERROR ERROR: Some charts failed to install and were rolled back
2019-01-07 16:17:36 root[25426]    ERROR  - metrics-server
```
> Outputting Exception from charts as a logging error message.  Fixes #33

- CHANGELOG.md
- reckoner/chart.py
- reckoner/helm/client.py
- reckoner/helm/tests/test_client.py
- reckoner/meta.py
To install cert-manager from their GitHub repository, we need to pull dependencies from their chart repo.
I re-implemented the `helm dependency update` call before installing the chart.
Try with
```yaml
minimum_versions:
helm: 2.12.1
reckoner: 0.10.2
charts:
cert-manager:
repository:
git: https://github.com/jetstack/cert-manager
path: contrib/charts
version: release-0.5
namespace: kube-system
```
> Reintroduce Helm dependency update before chart install

- CHANGELOG.md
- reckoner/chart.py
- reckoner/cli.py
- reckoner/config.py
- reckoner/helm/client.py
- reckoner/meta.py
- reckoner/reckoner.py
- reckoner/tests/test_cli.py
- tests/test_reckoner.py
* Adjusted naming of hack_merge variable
* Added information to the deprecation warning
* Adjusted the deprecation to be fired last after the final hook (so it is easily noticed)
* More tests to assure we avoid breaking changes to the CLI params and arguments
* A new `set-values: {}` key in the chart config to use for settings `--set` for helm
In the future, the `values: {}` configuration of a chart will change it's
behavior (see Issue #7). The current behavior translates any `values:{}` into
`--set` for the command line helm. This makes certain object types lose their
type fidelity. This means `true` becomes `string("true")` when pushed through
`--set values=true`. To maintain the same behavior for your settings please
change `values:{}` to `set-values:{}`. This behavior deprecaton will …
> Release Candidate for 1.0.0 (RC1)

- CHANGELOG.md
- reckoner/cli.py
- reckoner/course.py
- reckoner/exception.py
- reckoner/reckoner.py
- reckoner/tests/test_reckoner.py
- tests/test_reckoner.py
Reckoner now raises an error to the user and is handled gracefully by click.
* Added error handling to click plot command to expect reckoner exceptions
* Fixed inheritance of reckoner exceptions
* Added tests around this new behavior
* Added testing to assure if at least a single chart in --only is correct, the run still succeeds but warns you at the end of missing charts
* Removed mention of "rollback" - because it hasn't worked since the reckoner rename
> Fixed error handling

- CHANGELOG.md
- reckoner/chart.py
- reckoner/command_line_caller/__init__.py
- reckoner/command_line_caller/tests/test_command_line_caller.py
- reckoner/helm/tests/test_provider.py
- reckoner/reckoner.py
- reckoner/tests/test_chart.py
#59 is addressed in this PR
Behavior today was only showing output of hooks, regardless of failure, in the debug output. We fixed up the handling of errors to match what the call() function returns. This now checks for exit success and will log stderr and stdout if there is anything to bubble up.
> Fixing issue 59

- CHANGELOG.md
- reckoner/chart.py
- reckoner/cli.py
- reckoner/command_line_caller/__init__.py
- reckoner/command_line_caller/tests/test_command_line_caller.py
- reckoner/config.py
- reckoner/course.py
- reckoner/exception.py
- reckoner/helm/tests/test_provider.py
- reckoner/reckoner.py
- reckoner/tests/test_chart.py
- reckoner/tests/test_cli.py
- tests/test_reckoner.py
This changes the behavior to run the hooks from the course.yml directory by default. You can still define absolute paths, but all relative paths should start from where course.yml exists. This is how I understand most implementation are today (either absolute or relative to course.yml).
> Run hooks from course.yml directory

- reckoner/config.py
The dirname() was returning "" empty white space which was causing subprocess to try and cd to "" dir which cannot exist. This may not have been caught if ./ was used in testing
> Fix hook execution path

- CHANGELOG.md
- reckoner/chart.py
- reckoner/course.py
- reckoner/meta.py
- reckoner/tests/test_chart.py
- reckoner/tests/test_course.py
Overview of the breaking change I made here.
1. I changed the contract of the call() function
so it always returns a response even if the
exitcode was not 0. (this was a change from before)
The intent was so that we can run commands and decide
what to do upstream depending on exitcode or other
information.
2. The tests I wrote actually should have been bubbling up
errors from the run_hook() method, since we are not
throwing the error at call().
I have added tests to make sure we throw errors with
non-zero exit codes.
> Fixing broken hook runs

- .circleci/config.yml
- tests/requirements.txt
Pipeline is currently broken because nose2 sometimes doesn't load the mock (WAT?)
I am going to be retagging this merge as v1.0.2 due to the problems with the pipeline currently. 
How to reproduce the error:
```
nose2   # This fails same as CI does
nose2 -s reckoner/tests # This passes and it runs the test that fails in the previous command
pytest # always works 
```
When debugging i could see that the mock wasn't being instantiated with nose2 when running from root. When you add a start directory to nose2, it *does* use the mock, which is super weird and inconsistent. 
I'm opting to move this all to pytest instead of figuring out why nose2 isn't working.
> Pytest change

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- development-requirements.txt
- reckoner/tests/test_meta.py
- setup.cfg
- setup.py
- tests/requirements.txt
* Migrated the ci pipeline to use pip install --user
* Removed unneeded settings from circleci
* Removed tests/requirements.txt and added the items to development-requirements.txt
* Refactored the versioning to be driven by nearest git tag
Git tags now drive the pip version, which will:
* Help understand if you've installed from the source and have a dirty or modified version (it's listed in pip now with the commit sha if it's N commits away from nearest version)
* Help ease versioning burden by just tagging the release and not having to update meta.py or setup.py
> Dynamic versioning

- .circleci/config.yml
- CHANGELOG.md
- end_to_end_testing/basic.yml
- setup.py
- Added a full end-to-end test with installing charts with reckoner on python 2 & 3
- Added a basic yaml course to test with
> MVP: Added End to End testing of Reckoner

- CHANGELOG.md
- reckoner/chart.py
- reckoner/tests/test_chart.py
Fixing issues with #82 
Allows you to define specs that may have `$(VAR)` in the definition. Previous behavior would send a stacktrace to the user. 
See [this link](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config) for usage example.
> Fixing interpolation

- .circleci/config.yml
Apparently all tags are skipped by default unless you had the filters enabled :man_facepalming:
> fix pipeline

- .circleci/config.yml
Apparently there has to be a relationship all the way downstream for any workspaces. Even though we're building and uploading the darwin build earlier in the jobs, it doesn't show up as accessible to the last "publish-binaries" job since it doesn't have a technical inheritance.
> Added dependencies

- .circleci/config.yml
- CHANGELOG.md
- reckoner/chart.py
- reckoner/tests/test_chart.py
- tests/test_reckoner.py
Some of the plugin ecosystems parse opts with bash and thus sometimes can get hung up on `-f=this.file` vs `-f this.file` -- with the error "Cannot find file: "=this.file".
The Popen module should handle all necessary escaping by default with anything passed into args so even setting `--set my_key=has spaces in value` should be handled correctly.
> WIP Refactored the helm arguments to implement spaces

- .circleci/config.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- reckoner/command_line_caller/tests/test_command_line_caller.py
- setup.py
This removes the ability to install Reckoner in a python2 environment. There are notes in both the README and CONTRIBUTING docs, as well as disabling python2 in the setup.py.  CI for python2 has also been removed.
Example output when trying to pip install in python2:
```
reactiveops/reckoner   sudermanjr/deprecate-python-2 ✘   .venv-2 
└─ pip install .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing /Users/asuderma/repos/reactiveops/reckoner
ERROR: reckoner requires Python '~=3.6' but the running Python is 2.7.15
```
Setup.py changes based on docs here: …
> Deprecating Python2 and requiring ~=3.6

- .circleci/config.yml
The latest python 3.7 image that CircleCI provides breaks pyinstaller reckoner binaries.
```[1808] Error loading Python lib '/tmp/_MEIT640ZK/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIT640ZK/libpython3.7m.so.1.0)```
This is due to the official python images switching to Debian 10 (buster). This PR pins the CircleCI executors to run on a Debian 9 (stretch) image.
> updated circle image to use Debain 9 stretch

- reckoner/reckoner.py
Looks like during our helm3 detection we accidentally commented this out and it should be un-commented until we get full helm3 detection support.
> Added back in server checking

- README.md
It looks like we started requiring `namespace` in the top-level. Was this intentional? Seems unnecessary if each chart defines its own namespace.
> Fix Quickstart

- CHANGELOG.md
- end_to_end_testing/run_end_to_end.sh
- end_to_end_testing/test_git_chart.yml
- reckoner/course.py
- reckoner/repository.py
- reckoner/tests/test_course.py
Fixes #152 
Quick synopsis of #152 is that the `repositories` settings in the course schema behaves differently than setting the same settings in each chart `repository` key/value. In order to try to normalize the behavior, but still keep some existing behavior, I've added a "reconciliation" step to the course parsing. Now when a chart has a string set, it will try to resolve the string to the key set in the `repositories: {}` section at the root of the document. If that repository key name does not exist, it will just leave it alone and keep the string in place (current behavior). If the key _does_ exist, then the course will replace the string with the repository configuration.
- Added fix to provide a chart name and version when installing repos at the whole course level
- Added a …
> Fixes for repository/repositories settings with git

- docs/README.md
Changed command to get current context from `kubectl get current-context` to `kubectl config current-context`
> fixed kubectl command in README to get current context

- end_to_end_testing/setup_common.sh
- end_to_end_testing/test_env_var.yml
- reckoner/chart.py
- reckoner/yaml/handler.py
- tests/test_course.yml
- update to kind 0.7.0 for e2e tests
- update kube to 1.15.7
- add e2e and unit testing coverage for deeply-nested comments inside of `values`
> Fixes #173. Regex the comments out before interpolating env vars.

- reckoner/repository.py
Resolves #54 
I will write a test for this.
course.yml I used to repro:
```yaml
---
namespace: testo
charts:
helloworld:
repository: ../../../../../../../../../src/fairwinds
```
> Don't try to add repos without a URL

- reckoner/config.py
- reckoner/tests/test_config.py
- tests/test_reckoner.py
Reset `Config` between test runs.
Default to '.' as Config.course_base_directory when no course file is set.
Context:
Some amount of the current tests rely on side effects of other tests to pass. 
```shell
❯ pytest tests/test_reckoner.py::TestCourseMocks::test_passes_if_any_charts_exist
=============================================== test session starts ================================================
platform darwin -- Python 3.7.3, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /Users/hopson/src/fairwinds/reckoner
plugins: cov-2.7.1
collected 1 item
tests/test_reckoner.py F                                                                                     [100%]
===================================================== FAILURES ===================================================== …
```
> Add reset() classmethod to Config.

- development-requirements.txt
- reckoner/helm/tests/test_client.py
- reckoner/helm/tests/test_provider.py
- reckoner/tests/test_chart.py
- reckoner/tests/test_cli.py
- reckoner/tests/test_config.py
- reckoner/tests/test_course.py
- reckoner/tests/test_hooks.py
- reckoner/tests/test_kube.py
- reckoner/tests/test_reckoner.py
- tests/test_reckoner.py
> mock is now part of the Python standard library, available as unittest.mock in Python 3.3 onwards.
`test_config` was the only required code change.
> Use unittest.mock

- reckoner/kube.py
Don't create or manage namespace when the --dryrun flag is present
I added a guard around the NamespaceMabnager().create_and_manage() method to so that the steps are never run when the dryrun flag is set
Fixes #203
> Make NamespaceManager respect --dryrun

- reckoner/cli.py
See: #205 .
Offers a bit more of a verbose prompt when Reckoner hits a snag and the user could benefit from seeing more information about what's wrong. The help doc for using the `log-level=DEBUG` needed to be updated, too.
(I'm hoping that `\n` line break style works for Click styles (`click.style()`)...?
If it doesn't or if this is not preferred, I'll just remove those -- I just love having line breaks in error messages; and a double-quoted string should accept `\n`, shouldn't it..?)
I also updated the help doc to match the suggested command.
> Make more verbose/helpful output for `--log-level=DEBUG`.

- docs/README.md
- reckoner/chart.py
- reckoner/kube.py
The machinery was already in place, I switched it on, added a little more in the docs, and updated the log level for when chart level namespace manangment is set to overwrite
> Enable chart level Namespace Manager

- docs/README.md
- reckoner/chart.py
- reckoner/cli.py
- reckoner/course.py
- reckoner/helm/client.py
- reckoner/reckoner.py
- tests/test_reckoner.py
This PR adds the `template` command through Reckoner. Since a lot of the machinery needed for `plot` was reusable, there was a fair amount of refactoring to keep things dry-er. Template itself just `print`s the tempalte output to stdout instead of logging because logging in python goes to STDERR. This means you can `reckoner template -o <chart> course.yml > manifests.yml` and you'll get a file with yaml and still see all the logs. 
I elected to make `-o` required thinking that one probably does not want to template out the entire reckoner file but I'm on the fence about it. Happy to hear feedback.
> Add Helm Template

- README.md
- docs/README.md
- end_to_end_testing/run_end_to_end.sh
- reckoner/cli.py
- reckoner/tests/test_cli.py
Makes either --run-all or --only required. Running `reckoner plot course.yml` with no arguments will now produce an error.
This applies to both the `plot` and `template` commands
```
-a, --run-all                   Run all charts in the course. Mutually
exclusive with 'only'.
-o, --only, --heading <chart>   Only run a specific chart by name Mutually
exclusive with 'run_all'.
```
```
└─ reckoner plot course.yaml -o foo -a
Error: Illegal usage: 'only' is mutually exclusive with 'run_all'.
```
Fixes #186
> MAJOR (potentially breaking)  Add --run-all. Make either run-all or only required.

- reckoner/chart.py
- reckoner/config.py
- reckoner/helm/client.py
- reckoner/helm/tests/test_client.py
- reckoner/repository.py
- tests/test_reckoner.py
Somewhere along the line we stopped using HELM_HOME as the location for the git based chart checkout and it cause some intermittent issues. 
This creates a way for reckoner to determing the cache location form helm since they are different in helm 2 and 3 so we use the one that the helm command is usint
> Improve Helm Repository Cache Location

- docs/README.md
- end_to_end_testing/run_end_to_end.sh
- reckoner/chart.py
- reckoner/cli.py
- reckoner/config.py
- reckoner/course.py
- reckoner/manifests.py
- reckoner/reckoner.py
- reckoner/tests/files/configmap.yaml
- reckoner/tests/files/service.yaml
- reckoner/tests/files/templates.yaml
- reckoner/tests/files/templates2.yaml
- reckoner/tests/files/templates3.yaml
- reckoner/tests/test_cli.py
- reckoner/tests/test_config.py
- reckoner/tests/test_manifests.py
- reckoner/yaml/handler.py
This adds `diff` to the list of commands. It compares
the output of `template`  and  `get_manifests`  using `difflib` . Whereas
most other commands return a `HelmCommandResponse` response, that was not
really work able without major re-write here because there is only a single
instance of `self.response`  in the  class. Calling `template`  and
`get_manifests` in succession from an instnace of the Chart class
overwrites the previous command's `self.response` . Less than ideal, but I
created hidden methods to return the content of those commands that are
then called by the new `diff`  command and I return the string
representation of the diff as `self.resposne`  but it is not an instance of
HelmResponse becaue it is not, technically, a HelmResponse
> Adding Diff command

- reckoner/chart.py
- reckoner/cli.py
removing dryrun from reckoner tempalte, its not necessary, removed dryrun from update, also unnecsasary, still gated the debug args in the get-manifest flow because it breaks stuff if its there
Fixed #221
> Adjust dry-run behavior for update, get-manifest, template

- reckoner/cli.py
Somewhere along the line, I realised this would work. I like this better. It only declares each option/argument once then it is re-used as a decorator for each CLI function.
> DRY options and args

- reckoner/manifests.py
There is an edge during a `diff` here when a chart generates an empty yaml document. In that case `document` ends up being `None` and that leads to eventually trying to do `self.document.get('metadata')` in `def manifest(self)` which promptly explodes. This just removes empty manifests from the list of all manifests early in the process.
> Handle case where chart generates an empty yaml doc

- docs/README.md
I'm using a helm chart with a path different from its name and ended up a bit confused. After reading the source code a tiny bit, I figured it out and suggest adding a tiny comment in the doc about it
> docs/README.md : Add a minor comment on git sparse checkout

- reckoner/cli.py
- reckoner/schema_validator/course.py
Examples:
```
▶ reckoner lint course.yml
No schema validation errors found.
```
```
▶ reckoner lint course.yml
2020-10-22 18:32:20  root[95557]    ERROR  while constructing a mapping
in "course.yml", line 2, column 1
found duplicate key "namespace" with value "foo" (original value: "demo")
in "course.yml", line 4, column 1
Duplicate key found while loading your course YAML, please remove the duplicate key shown above.
```
Fixes #232
> Adding a lint command

- reckoner/chart.py
- reckoner/cli.py
- reckoner/tests/test_chart.py
This PR fixes an issue where a certain kind of string.Template failure lead to false sucess condition where the environment variable would not be templated properly. 
Updating and consolidating error handling into the Chart._interpolate_env_vars_from_string method. Forcing template failure to be a critical failure
Fixes #242
> Condolidate Env Var Interpolation

- reckoner/chart.py
- reckoner/repository.py
This PR updates the error passing for failures in git commands when pulling repostories.
It raises errors, refines the errors raised and removes unnecessary repetition in traceback and in logging
It also fixes a bug where the missing branch logic was never triggered because of an extra '.' messing up the string match
Fixes #176
> Add Better Error Messaging for Git Repositories

- reckoner/assets/course.schema.json
In [./reckoner/chart.py:95](https://github.com/FairwindsOps/reckoner/blob/7e61ab04ea7eea5b82fc15283db0378e0fad1c74/reckoner/chart.py#L95) the course field `plugin` is extracted:
```python
self._plugin = self._chart.get('plugin')
```
But the [schema](https://github.com/FairwindsOps/reckoner/blob/7e61ab04ea7eea5b82fc15283db0378e0fad1c74/reckoner/assets/course.schema.json#L101) does not allow this, but only `plugins`, which is not used at all:
```json
"plugins": {
"type": "string"
},
```
This results in the plugin functionality (e.g. with the helm plugin `secrets`) not working at all:
```yaml
context: minikube
namespace: default
repositories:
regcred-secrets:
git: git@gitlab.com:Instaffo/infrastructure/kubernetes/helm-charts/regcred-secrets.git
charts:
my-chart:
version: 0.1.0
repository: …
```
> Fix course schema `plugin` field

- reckoner/course.py
Gets namespace from the chart and defaults to the course level one for log display
Fixes #269
> Fix 269 - Show correct namespaces in log

- reckoner/chart.py
Now, when  plot is called the new chart version number will be displayed in the first like of the outuput (if specified in the course)
Fixes #170
```
2021-01-24 17:00:36 C02DG0SRMD6R root[41571] INFO Release "redis-one" has been upgraded to 12.6.3. Happy Helming!
NAME: redis-one
LAST DEPLOYED: Sun Jan 24 17:00:35 2021
NAMESPACE: foo
STATUS: deployed
```
> Fix 170 - Add new version number to the output

- end_to_end_testing/course_files/24_test_no_context.yml
- end_to_end_testing/tests/24_no_context.yaml
- reckoner/chart.py
- reckoner/cli.py
- reckoner/course.py
- reckoner/helm/client.py
This PR imporves error handling and out put for the `get-manifests` command and, but extenation, the diff and upgrade commmand as well.Also, a couple typos, and formatting.
Fixes #273
> Fix 273 - fail when context does not exist

- reckoner/chart.py
This PR fixes the issue where `diff` was not respecting the environment variable in the context.
It was due to the bespoke argument list in the `get_manifests` method. I added `_check_env_vars` there to replace the
envvars in the bespoke list. This was done by the `_pre_command` method already, but since the new arg list was created _after_,
it needs to be run again, or something like it.
Fixes #264
> Fix 264 - Env Var in context for diff

- docs/usage.md
The doc states the `helm_args` top-level key is a string, but it seems an array of string is required (looks nicer to me anyway 👍 )
> doc: helm_args is a list of string

- reckoner/chart.py
- reckoner/course.py
- reckoner/kube.py
- reckoner/tests/namespace_manager_mock.py
- reckoner/tests/test_kube.py
Fixes #468
This leverages the context portion of setting up the kubernetes client in the `NamespaceManager` object. Therefore, if we hit the kubernetes namespace management code it will properly set a context if it exists in the kube config, but will give a useful error if the context does not exist in the kube config:
```
2021-09-13 10:28:13 luke-macbook-fw.local root[98514] INFO Found Helm Version 3.3.4
2021-09-13 10:28:30 luke-macbook-fw.local root[98514] INFO Running 'install' on rbac-manager in rbac-manager
2021-09-13 10:28:30 luke-macbook-fw.local root[98514] ERROR Unable to load kubernetes configuration
2021-09-13 10:28:30 luke-macbook-fw.local root[98514] ERROR ERROR: install Failed on rbac-manager
2021-09-13 10:28:30 luke-macbook-fw.local root[98514] ERROR Invalid kube-config …
```
> namespace management should utilize kube context

- end_to_end_testing/run_go.sh
- pkg/reckoner/namespace.go
Because we already populate the default namespace for a given release during the course file parse there's no need to try and create it here. It will be created in the forloop below the removed code.
This should fix some of the e2e tests because it was attempting to create the default namespace twice before.
> [RD-34] Fix default namespace management

- cmd/root.go
- end_to_end_testing/tests/01_basic.yaml
- pkg/reckoner/diff.go
- pkg/reckoner/plot.go
- pkg/reckoner/update.go
- move some diff functionality to a new function to only get individual diff string
- no need to return a string from the client.Plot() method because we never returned anything from it
- add update command to only run upgrades on releases that have diffs
> [RD-35] Add update command

- cmd/root.go
- pkg/course/course.go
- pkg/course/course_test.go
- pkg/reckoner/plot.go
Also changed in this PR:
* make conversion from v1 to v2 schema a private function since everything should happen with the OpenV2 function.
* changed all klog.Fatal() calls in the cmd package to red error output with exit code of 1 instead
* `reckoner convert` command no longer calls the ConvertV1toV2 function and instead simply uses OpenV2 function.
> [go] parse environment variables

- .circleci/config.yml
- cmd/root.go
- end_to_end_testing/course_files/05_test_exit_on_post_install_hook.yml
- end_to_end_testing/course_files/10_test_git_chart.yml
- end_to_end_testing/course_files/15_test_default_namespace_annotation_and_labels.yml
- end_to_end_testing/tests/04_bad_chart.yaml
- end_to_end_testing/tests/07_good_hooks.yaml
- end_to_end_testing/tests/13_schema.yaml
- end_to_end_testing/tests/15_namespace_management.yaml
- end_to_end_testing/tests/21_diff.yaml
- go.mod
- pkg/course/course.go
- pkg/course/course_test.go
- pkg/helm/helm.go
- pkg/reckoner/client.go
- pkg/reckoner/diff.go
- pkg/reckoner/git.go
- pkg/reckoner/hook.go
- pkg/reckoner/namespace.go
- pkg/reckoner/namespace_test.go
- pkg/reckoner/plot.go
- pkg/reckoner/plot_test.go
- pkg/reckoner/update.go
To fix most e2e tests for the go rewrite by adding the git repository
management feature and fixing some bugs that were uncovered by these
tests.
Also removed all python testing from the circleci config and temporarily
commented out the release workflow until we are ready to release the go
version.
> Refactoring go version and many fixes for e2e tests

- pkg/course/course.go
- pkg/reckoner/plot.go
- pkg/reckoner/plot_test.go
This PR fixes #527
Fix `files` section of the release declaration so it works
> [Go] fix file-based values declarations

- cmd/root.go
- end_to_end_testing/tests/24_no_context.yaml
- pkg/reckoner/client.go
Make use of the toplevel chart key `context` so we use the configured kubecontext. If it does not exist in the kubeconfig, we should bail out.
> [go] fix kubecontext checking

- .circleci/config.yml
- .goreleaser.yml
- Dockerfile
- Dockerfile-go
This PR fixes #531
Update CI to our standards.
- Replace original Dockerfile with the Dockerfile-go and remove Dockerfile-go
- Update .goreleaser.yml to include prereleases, cross-arch builds, and signing
- Update circleci to account for all of this.
- Push images to gcr instead of quay
- remove the `go-` from the docker tags in gcr
NOTE:
I used a different regex for the release steps. I think we shouldn't be publishing docs on release candidates, so I filtered them out. We run goreleaser on all valid `vx.x.x` tags.
n/a
> udpate CI for cross-arch docker, release candidates

- cmd/root.go
- cmd/update.go
- cmd/version.go
- end_to_end_testing/tests/07_good_hooks.yaml
- end_to_end_testing/tests/10_git_charts.yaml
- end_to_end_testing/tests/13_schema.yaml
- end_to_end_testing/tests/21_diff.yaml
- go.mod
- go.sum
- pkg/course/course.go
- pkg/helm/helm.go
- pkg/reckoner/client.go
- pkg/reckoner/plot.go
A couple of bugfixes in the golang version from testing. Updated tests. Added an update-cli command
- New command for updating cli
- Moved git repo clone logic into function and called it from both template and plot
- Output colorized output to stderr so that reckoner template is more useful
> Bugfixes. Add update-cli command

- pkg/course/course.go
- pkg/course/course_test.go
Previous logic put the `$$` back, rather than replacing it with a single `$`
One character removed in the output of the check, and fixed the test.
> Fix to the env var escaping

- cmd/root.go
- pkg/course/course.go
This PR fixes #577
When running `reckoner convert`, we shouldn't parse environment variables
Added a package variable to disable env parsing
There's likely a cleaner way to do this, I'm not overly happy about using a global for this, but due to the extreme ways in which we have to have to handle yaml, this may be necessary
> Don't parse env on convert command

- pkg/course/course.go
- pkg/course/namespace.go
- pkg/course/namespace_test.go
- pkg/course/shellSecrets_test.go
- pkg/course/testdata/v2_namespace.yaml
This PR fixes #568
- Reorganized the namespace code slightly. 
- Added unit tests to cover this test case
- Added some other unit tests that were low-hanging fruit in the course package (66.3% coverage on course)
- Fixed the merge namespace function to not modify the original defaults object
n/a
> Fix namespace management

- pkg/course/shellSecrets_test.go
make the tests for shells work universally. they were failing on some Ubuntu-based distros at the least.
The original test just made sure the result of `newShellExecutor()` matched an object hardcoded in `Test_newShellExecutor()`.
Now we independently test the attributes of the resulting object against what we want from the test, using a regex to test `got.Executable` and EqualValues for `got.Args`, respectively.
We talked about supporting a list of possible places to expect `echo` on a distribution, but what if the system configuration is valid and functional, but we didn't include support? Ultimately we decided to go with a regex so we likely won't have to look at this again for a long, long time.
> make shell test work universally (hopefully)

- end_to_end_testing/course_files/10_test_git_chart.yaml
Tests started failing right after bitnami removed a bunch of old charts from their index. The end to end test for git charts referenced an older version of the goldilocks chart, which had a reference to a removed metrics-server chart version.
This PR will fix the test
Updated the revision of the goldilocks chart to the latest HEAD on the charts repo
n/a
> Fix the reference to an old goldilocks chart that referenced a removed bitnami chart

- pkg/course/argocd.go
- pkg/course/course.go
- pkg/reckoner/plot.go
It's common with certain applications to ignoreDifferences for specific things. The use-case I have is to ignore it in the prometheus chart, which has a process to modify the webhook failurePolicy after creation, which confuses argoCD.
Added the argocd structs for ignoreDifferences
Also fixed a linter error related to the ioutil package
n/a
> Add the ability to ignoreDifferences in an argoCD application manifest

- .circleci/config.yml
- end_to_end_testing/course_files/10_test_git_chart.yaml
Fixes the CI
Remove the pinned docker version that is breaking things in later versions of Circle
n/a
> Remove pinned docker version and fix e2e test

- pkg/course/course.go
Currently, if the marshalling the file to JSON fails, reckoner returns a non-descriptive error.
```
failed to validate jsonSchema in course file: course.yml
Course file has schema validation errors - error opening course file course.yml: Course file has schema validation errors
```
This PR changes that error to:
```
Course file has schema validation errors - error opening course file course.yml: unable to parse secrets: yaml: line 3: mapping values are not allowed in this context
```
Instead of passing the generic SchemaValidationError, we pass back the actual error. The SchemaValidationError is only used if there are actual schema validation errors.
n/a
> surface any errors encountered during schema validation
