reckoner/chart.py
reckoner/helm.py

added info level logging for stdout from all helm calls

---

CHANGELOG.md
README.md
reckoner/chart.py
reckoner/cli.py
reckoner/config.py
reckoner/course.py
reckoner/example-course.yml
reckoner/helm.py
reckoner/meta.py
reckoner/reckoner.py
tests/test_course.yml
tests/test_reckoner.py

Lots of small readability, formatting, white space, and typo fixes.
Specifying helm-args in cli overrides the course yaml file (with warnings)
Added helm_args to the test course.yml and added them to the test.
Warnings about deprecating --debug

Addding the ability to specify global helm args in course.yml

---

CODEOWNERS

The gates are open to adding code-owners - please add yourself in here for review if you want to be a code owner. :)

Added codeownership

---

setup.py

GitHub says this is an issue - pyyaml < 4.2b1 has CVE-2017-18342

Added fix for recommended CVE on PyYAML

---

CHANGELOG.md
reckoner/chart.py
tests/test_reckoner.py

closes #34
Fixes regress where value-strings from course.yml are not translated to set-string on the command line.

Fixes set-string, re-enabled tests for it.

---

CHANGELOG.md
reckoner/chart.py
reckoner/meta.py

Also don't need to raise the error, it is already logged.

Fixes #43.  Files is a list not a dict.  

---

CHANGELOG.md
reckoner/course.py
reckoner/meta.py
reckoner/tests/test_course.py
tests/test_course.yml
tests/test_reckoner.py

when calling _compare_required_versions

Fixes #40.  Handle the minimum error exception 

---

examples.md

I confirmed that both statsd and APM work with this setup.

Update Datadog statsd example

---

reckoner/__init__.py
reckoner/chart.py
reckoner/cli.py
reckoner/command_line_caller/__init__.py
reckoner/command_line_caller/tests/__init__.py
reckoner/command_line_caller/tests/test_command_line_caller.py
reckoner/config.py
reckoner/course.py
reckoner/exception.py
reckoner/helm/__init__.py
reckoner/helm/client.py
reckoner/helm/cmd_response.py
reckoner/helm/command.py
reckoner/helm/provider.py
reckoner/helm/tests/__init__.py
reckoner/helm/tests/test_client.py
reckoner/helm/tests/test_cmd_response.py
reckoner/helm/tests/test_provider.py
reckoner/meta.py
reckoner/reckoner.py
reckoner/release.py
reckoner/repository.py
reckoner/tests/__init__.py
reckoner/tests/test_chart.py
reckoner/tests/test_cli.py
reckoner/tests/test_config.py
reckoner/tests/test_course.py
reckoner/tests/test_reckoner.py
tests/__init__.py
tests/test_reckoner.py

Testing out a new plugin for future work

Added licenses to all files where it was missing

---

README.md

I think this is correct after looking at a few examples.

Update README.md - fix hooks syntax

---

.circleci/config.yml
CHANGELOG.md
reckoner/cli.py
reckoner/tests/test_cli.py
setup.py

* Updated GitPython, coloredlogs, and semver to use greater than or equal to latest

Added dependency updates

---

CONTRIBUTING.md
README.md

Added docs for dev env and release for python3

---

.circleci/config.yml
CHANGELOG.md

Adding a workflow job to upload our compiled assets to the release in github.

Adding pipeline to upload github releases

---

README.md

adding preferred binary download installation instructions. fixes #102

adding preferred binary download installation instructions. fixes #102

---

README.md
ROADMAP.md

Quickstart example isn't currently working. Grafana installs, but Polaris fails.

add roadmap, quickstart

---

README.md

Sorry for the noise - noticed the readme was a bit confusing after I merged the last PR

minor tweak to readme

---

.circleci/config.yml
end_to_end_testing/setup.sh

Changes
- Adjusted where the binaries upload to (org rename change)
- Pinned versions of kubernetes, kind and helm in pipeline end to end tests

Changes to CI

---

README.md

changed permissions instructions from `chmod -x` to `chmod +x`

fixed permission instruction in binary install method

---

CHANGELOG.md
README.md
end_to_end_testing/run_end_to_end.sh
end_to_end_testing/test_env_var.yml
end_to_end_testing/test_strong_typing.yml
reckoner/chart.py
reckoner/cli.py
reckoner/course.py
reckoner/reckoner.py
reckoner/tests/test_chart.py
reckoner/tests/test_course.py
reckoner/yaml/handler.py
reckoner/yaml/tests/test_handler.py
setup.py
tests/test_course.yml
tests/test_reckoner.py

Added the ability to keep types strong by using the `values: {}` section of a chart config. Now the `set-values` and `values` blocks have different behavior underlying.
**Breaking Changes**
The `chart: {values: {}}` config block and `chart: {set-values:{}}` config block now have different behavior. `set-values: {}` always gets translated into `helm` arguments as `--set key=value`. The `values: {}` now gets applied to `helm` arguments as `-f temporary_values_name.yml`. The `values: {}` config block is now fully consistent with intended types and would behave as though you are using a `-f my_values.yml` in your `helm` command. Prior to this change you would see inconsistent type casting for float, bool and integer config settings.

Added strong type support for course.yml

---

docs/README.md
reckoner/assets/course.schema.json
reckoner/chart.py
reckoner/cli.py
reckoner/course.py
reckoner/hooks.py
reckoner/tests/test_chart.py
reckoner/tests/test_course.py
reckoner/tests/test_hooks.py

refector of hooks, adding concept of course hooks, refactoring tests related to hooks, reorganizing some imports

Adding Course pre and post install hooks

---

codecov.yml

I think this makes sense to do and gives a better picture of coverage changes.

skip tests from coverage

---

.circleci/config.yml
README.md
end_to_end_testing/setup_helm2_12_0.sh
end_to_end_testing/setup_helm3.sh

Updated tests and README to include supported versions of Helm.

Update supported helm versions

---

reckoner/config.py
reckoner/repository.py
reckoner/tests/test_repository.py

Add some simple repository tests for #54

Test repository

---

end_to_end_testing/run_end_to_end.sh
reckoner/chart.py
reckoner/cli.py
reckoner/course.py
reckoner/reckoner.py
reckoner/tests/test_chart.py
reckoner/tests/test_cli.py
reckoner/tests/test_reckoner.py

I realized that there were some mistakes in the get-manifest PR and this should address them

Fixing template and get-manifests

---

.circleci/config.yml
reckoner/chart.py
reckoner/cli.py
setup.py

Darwin binary - https://3115-159374996-gh.circle-artifacts.com/0/reckoner-darwin
Linux Binary - https://3114-159374996-gh.circle-artifacts.com/0/reckoner-linux-amd64

Fix binary compilation. Add a python 3.8 build test

---

reckoner/helm/client.py

Add deprecation warning when helm2 is used

---

docs/README.md
reckoner/chart.py

Example:
```
2020-10-22 18:19:11  root[88650]  WARNING  DEPRECATION NOTICE: set-values will be removed in favor of values in a future release. Please migrate your course file
2020-10-22 18:19:11  root[88650]  WARNING  DEPRECATION NOTICE: values-strings will be removed in favor of values in a future release. Please migrate your course file
```
First step for #233

Deprecation warnings on set-values and values-strings

---

end_to_end_testing/course_files/test_diff.yml
end_to_end_testing/tests/21_diff.yaml
reckoner/chart.py
reckoner/course.py

This PR ensurse that `diff` will respect the course level namespace. `args` were not being passed through properly. this PR fixes that for `diff` and `update` and addes e2e tests for `diff`

Respect Default Course Namespace for `diff` Command

---

end_to_end_testing/course_files/strong_typing.yml
end_to_end_testing/course_files/test_after_first_failure.yml
end_to_end_testing/course_files/test_bad_schema_repository.yml
end_to_end_testing/course_files/test_basic.yml
end_to_end_testing/course_files/test_create_namespace.yml
end_to_end_testing/course_files/test_default_namespace_annotation_and_labels.yml
end_to_end_testing/course_files/test_does_not_overwrite_namespace_annotation_and_labels.yml
end_to_end_testing/course_files/test_dont_overwrite_ns_meta.yml
end_to_end_testing/course_files/test_env_var.yml
end_to_end_testing/course_files/test_exit_on_post_install_hook.yml
end_to_end_testing/course_files/test_exit_on_pre_install_hook.yml
end_to_end_testing/course_files/test_failed_chart.yml
end_to_end_testing/course_files/test_git_chart.yml
end_to_end_testing/course_files/test_good_hooks.yml
end_to_end_testing/course_files/test_multi_chart.yml
end_to_end_testing/course_files/test_overwrite_namespace_annotation_and_labels.yml
end_to_end_testing/course_files/test_strong_ordering.yml
end_to_end_testing/course_files/testing_in_folder/test_files_in_folders.yml

This PR replaces all deprecated chart urls with approved versions in the test course.yml

Replace Deprecated URLs in Tests

---

README.md
end_to_end_testing/course_files/test_environment_variable_namespace_on_chart.yml
end_to_end_testing/tests/01_basic.yaml
end_to_end_testing/tests/23_chart_namespace_environment_variable.yaml
reckoner/chart.py
reckoner/yaml/handler.py
setup.py
tests/test_reckoner.py

This PR provides additional functionality to use environment variables in the namespace field of the chartblock.

Interpolate Env Var in Chart Namespace

---

docs/README.md
reckoner/chart.py
reckoner/repository.py

Just tightening up some stuff I found from when I was looking into an issue about repositories

Small Fixes

---

README.md
docs/README.md
end_to_end_testing/course_files/25_test_import.yml
end_to_end_testing/tests/25_import.yaml
reckoner/cli.py
reckoner/helm/client.py
reckoner/importer.py
reckoner/tests/test_importer.py

This adds an import command
Fixes #279
This is a first draft/sketch of the feature for feedback purposes. If this look acceptable, I'll add some tests and docs.

Fix 279 - Adding Import Command

---

.circleci/build.config
.circleci/config.yml
Dockerfile
reckoner/importer.py

My best guess at config to push this as a docker image. 
Requires extra work in the world and I'll be surprised if it work first try.

Docker Image Push

---

cmd/root.go
pkg/reckoner/validation.go
pkg/reckoner/validation_test.go

- make -run-all and --only mutually exclusive 
- Formatting changes my IDE complained about 
Fixes #295

Validate incoming args

---

pkg/course/course.go
pkg/course/course_test.go

Set default namespace and repository on opening course file.

---

reckoner/chart.py

This PR fixes an issue with dependency update for a local chart when the `reckoner` command is not run in the same directory as the `course.yml` file. The update was being excluded because thecode checking if a chart existed was relative to the command directory and not the the `course.yml`. This changes the chart path check to be absolute _and_ uses the `course.yml` location as it's starting point.
Fixes #325

Fix Dependency update path

---

.circleci/config.yml

Removed the PYPI_USERNAME hard-coding

Fix pypi config

---

reckoner/helm/client.py

Make the + in the semver regex optional

---

CODEOWNERS

Since I'll be participating more here, I think this makes sense :)

Add Luke to Codeowners

---

cmd/root.go
pkg/reckoner/client.go
pkg/reckoner/namespace.go

Flag to disable creating namespace

---

pkg/reckoner/client.go

Fixes #480
```
▶ ./reckoner-go template end_to_end_testing/course_files/01_test_basic.yml -o farglebargle -v10 
I1005 08:24:42.077110   91713 course.go:253] did not detect v2 course file - trying conversion from v1
I1005 08:24:42.077312   91713 course.go:258] WARNING: this course file was automatically converted from v1 to v2 - this functionality may be removed in the future
I1005 08:24:42.077324   91713 course.go:307] no default repository set - skipping filling out defaults
I1005 08:24:42.077357   91713 helm.go:37] found helm at /Users/asuderma/.asdf/shims/helm
I1005 08:24:42.077367   91713 client.go:116] no minimum helm version found, assuming okay
I1005 08:24:42.077373   91713 client.go:139] no minimum reckoner version found, assuming okay
F1005 08:24:42.077385   91713 root.go:104] no …
```

Check if release is in current list and fail if not

---

pkg/course/course.go

[go] do not drop minimum_versions when converting

---

reckoner/kube.py

Fix label typo in kube.py

---

docs/usage.md

add docs for deploying from a local filesystem

---

.circleci/config.yml

Use go 1.17 in circleci

---

end_to_end_testing/course_files/20_test_strong_ordering.yml
end_to_end_testing/tests/20_strong_ordering.yaml

attempt to get some useful feedback from flaky e2e test

---

cmd/root.go
end_to_end_testing/tests/24_no_context.yaml
pkg/course/course.go
pkg/course/testdata/convert1.yaml
pkg/reckoner/client.go

Some slight refactoring and adding back Unmarshal logic to preserve order of releases

---

docs/usage.md

Fix CLI Usage heading in docs

---

go.mod
go.sum

Thanks @kevinburke for the PR. Opening this to avoid conflicts and CLA stuff.

Update ssh_config. Go mod tidy

---

.circleci/config.yml

Conform to latest circleci standards

Stop enabling experimental features
